
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.3 EDK_P.40xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_GPIO_LCD_DEVICE_ID,
		XPAR_GPIO_LCD_BASEADDR,
		XPAR_GPIO_LCD_INTERRUPT_PRESENT,
		XPAR_GPIO_LCD_IS_DUAL
	}
};


