
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.3 EDK_P.40xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_CDCE913_I2C_DEVICE_ID,
		XPAR_CDCE913_I2C_BASEADDR,
		XPAR_CDCE913_I2C_TEN_BIT_ADR,
		XPAR_CDCE913_I2C_GPO_WIDTH
	}
};


